name: code_quality

# This is a Github Action workflow which checks code quality using pylint whenever a
# commit is made to master

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:

    # Checkout the code and install Python
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1

    # Run pylint
    - run: pip install -r requirements_dev.txt
    - run: pip install pylint
    - run: pylint **/*.py

